name: Daily News Report

on:
  schedule:
   # 01:20 UTC + 7 tiếng = 08:20 sáng giờ Việt Nam
    - cron: '20 1 * * *'
  workflow_dispatch:

env:
  # Ép toàn bộ runner dùng Node.js 24 để không còn cảnh báo vàng
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -U google-generativeai feedparser markdown

      - name: Run script
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: python news_bot.py
